name: sample_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.5 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  dashbook: ^0.1.6
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - >
    - packages/sample_project/assets/images/nicepngpasswordiconpng20731151.png
    - packages/sample_project/assets/images/line1.svg
    - >
      packages/sample_project/assets/images/kisspngcomputericonsuserprofile5afd955d62a2c81.png
